config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  
  Spree::Core::Engine.routes.draw do
    get "quienes", to: "info#quienes" 
    get "contacto", to: "info#contacto" 
  end
end

app/models/spree/address.rb
module Spree
  class Address < Spree::Base
    require 'twitter_cldr'

    NO_ZIPCODE_ISO_CODES ||= [
      'AO', 'AG', 'AW', 'BS', 'BZ', 'BJ', 'BM', 'BO', 'BW', 'BF', 'BI', 'CM', 'CF', 'KM', 'CG',
      'CD', 'CK', 'CUW', 'CI', 'DJ', 'DM', 'GQ', 'ER', 'FJ', 'TF', 'GAB', 'GM', 'GH', 'GD', 'GN',
      'GY', 'HK', 'IE', 'KI', 'KP', 'LY', 'MO', 'MW', 'ML', 'MR', 'NR', 'AN', 'NU', 'KP', 'PA',
      'QA', 'RW', 'KN', 'LC', 'ST', 'SC', 'SL', 'SB', 'SO', 'SR', 'SY', 'TZ', 'TL', 'TK', 'TG',
      'TO', 'TV', 'UG', 'AE', 'VU', 'YE', 'ZW'
    ].freeze

    belongs_to :country, class_name: "Spree::Country"
    belongs_to :state, class_name: "Spree::State"

    has_many :shipments, inverse_of: :address

    before_validation :clear_invalid_state_entities, if: -> { country.present? }, on: :update

    with_options presence: true do
      validates :firstname, format: { with: /\A[a-zA-Z]+\z/, message: "Solo se aceptan letras" } 
      validates :lastname, format: { with: /\A[a-zA-Z]+\z/, message: "Solo se aceptan letras" }
      validates :address1 
      validates :city, format: { with: /\A[a-zA-Z]+\z/, message: "Solo se aceptan letras" } 
      validates :country
      validates :zipcode, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
      validates :phone, format: { with: /\A[0-9]+\z/, message: "Solo se aceptan numeros" }
      validates :phone, length: { maximum: 9 }   
      validates :phone, length: { minimum: 7 }  
    end

    validate :state_validate, :postal_code_validate

    alias_attribute :first_name, :firstname
    alias_attribute :last_name, :lastname

    self.whitelisted_ransackable_attributes = %w[firstname lastname company]

    def self.build_default
      country = Spree::Country.find(Spree::Config[:default_country_id]) rescue Spree::Country.first
      new(country: country)
    end

    def self.default(user = nil, kind = "bill")
      if user && user_address = user.public_send(:"#{kind}_address")
        user_address.clone
      else
        build_default
      end
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
        name: full_name,
        address1: address1,
        address2: address2,
        city: city,
        state: state_text,
        zip: zipcode,
        country: country.try(:iso),
        phone: phone
      }
    end

    def require_phone?
      true
    end

    def require_zipcode?
      
    end

    private

    def clear_state_entities
      clear_state
      clear_state_name
    end

    def clear_state
      self.state = nil
    end

    def clear_state_name
      self.state_name = nil
    end

    def clear_invalid_state_entities
      if state.present? && (state.country != country)
        clear_state
      elsif state_name.present? && !country.states_required? && country.states.empty?
        clear_state_name
      end
    end

    def state_validate
      # Skip state validation without country (also required)
      # or when disabled by preference
      return if country.blank? || !Spree::Config[:address_requires_state]
      return unless country.states_required
      # ensure associated state belongs to country
      if state.present?
        if state.country == country
          clear_state_name # not required as we have a valid state and country combo
        elsif state_name.present?
          clear_state
        else
          errors.add(:state, :invalid)
        end
      end

      # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
      if state_name.present?
        if country.states.present?
          states = country.states.find_all_by_name_or_abbr(state_name)

          if states.size == 1
            self.state = states.first
            clear_state_name
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure at least one state field is populated
      errors.add :state, :blank if state.blank? && state_name.blank?
    end

    def postal_code_validate
      return if country.blank? || country.iso.blank? || !require_zipcode?
      return if !TwitterCldr::Shared::PostalCodes.territories.include?(country.iso.downcase.to_sym)

      postal_code = TwitterCldr::Shared::PostalCodes.for_territory(country.iso)
      errors.add(:zipcode, :invalid) if !postal_code.valid?(zipcode.to_s.strip)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/info_controller.rb
module Spree
	class InfoController < Spree::StoreController
		def quienes
		end
		def contacto
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spree/info_helper.rb
module Spree::InfoHelper
end

app/views/boleta_venta/_form.html.erb
<%= form_for(boleta_ventum) do |f| %>
  <% if boleta_ventum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boleta_ventum.errors.count, "error") %> prohibited this boleta_ventum from being saved:</h2>

      <ul>
      <% boleta_ventum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h5 class="text-center text-muted">
  <div class="field">
    <%= f.label :fecha %>
    <%= f.datetime_select :fecha %>
  </div>
</h5>
<h5 class="text-center text-muted">
  <div class="field">
    <%= f.label :monto %>
    <%= f.text_field :monto %>
  </div>
</h5>
<h5 class="text-center text-muted">
  <div class="field">
    <%= f.label :tipo_pago %>
    <%= f.text_field :tipo_pago %>
  </div>
</h5>
<h5 class="text-center text-muted">
  <div class="field">
    <%= f.label :cantidad %>
    <%= f.text_field :cantidad %>
  </div>
</h5>
<h5 class="text-center text-muted">
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</h5>

app/views/boleta_venta/show.html.erb
<p id="notice"><%= notice %></p>
<h5 class="text-center text-muted">
<p>
  <strong>Fecha:</strong>
  <%= @boleta_ventum.fecha %>
</p>
</h5>
<h5 class="text-center text-muted">
<p>
  <strong>Monto:</strong>
  <%= @boleta_ventum.monto %>
</p>
</h5>
<h5 class="text-center text-muted">
<p>
  <strong>Tipo pago:</strong>
  <%= @boleta_ventum.tipo_pago %>
</p>
</h5>
<h5 class="text-center text-muted">
<p>
  <strong>Cantidad:</strong>
  <%= @boleta_ventum.cantidad %>
</p>
</h5>
<h5 class="text-center text-muted"><%= link_to 'Editar', edit_boleta_ventum_path(@boleta_ventum) %></h5> |
<h5 class="text-center text-muted"><%= link_to 'Volver', boleta_venta_index_path %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>

<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <p class="form-group" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname do %>
      <%= Spree.t(:first_name) %><abbr class="required" title="required" >*</abbr>
    <% end %>

    <%= form.text_field :firstname, class: 'form-control required'  %>

  </p>


  <p class="form-group" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname do %>
      <%= Spree.t(:last_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :lastname, class: 'form-control required' , pattern:"[Aa-Zz]{1,20}", title: "Ingrese datos validos"%>
  </p> 

  
  <% if Spree::Config[:company] %>
    <p class="form-group" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %>
      <%= form.text_field :company, class: 'form-control' %>
    </p>
  <% end %>
  <p class="form-group" id=<%="#{address_id}address1" %>>
    <%= form.label :address1 do %>
      <%= Spree.t(:street_address) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :address1, class: 'form-control  required' %>
  </p>
  <p class="form-group" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %>
    <%= form.text_field :address2, class: 'form-control' %>
  </p>
  <p class="form-group" id=<%="#{address_id}city" %>>
    <%= form.label :city do %>
      <%= Spree.t(:city) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :city, class: 'form-control required' , pattern:"[Aa-Zz]{1,20}", title: "Ingrese datos validos" %>
  </p>
  <p class="form-group" id=<%="#{address_id}country" %>>
    <%= form.label :country_id do %>
      <%= Spree.t(:country) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, {class: 'form-control required'} %>
    </span>
  </p>

  <% if Spree::Config[:address_requires_state] %>
    <p class="form-group" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state do %>
        <%= Spree.t(:state) %><abbr class='required' title="required" id=<%="#{address_id}state-required"%>>*</abbr>
      <% end %>

      <%== state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {include_blank: true},
                            {class: have_states ? 'form-control required' : 'form-control hidden',
                            disabled: !have_states}) +
         form.text_field(:state_name,
                            class: !have_states ? 'form-control required' : 'form-control hidden',
                            disabled: have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
    </p>
      <noscript>
        <%= form.text_field :state_name, class: 'form-control required' %>
      </noscript>
  <% end %>

  <p class="form-group" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode do %>
      <%= Spree.t(:zip) %><% if address.require_zipcode? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.text_field :zipcode, class: "form-control #{'required' if address.require_zipcode?}" , pattern:"[0-9]{1,9}", title: "Ingrese datos validos" %>
  </p>
 <p class="form-group" id=<%="#{address_id}phone" %>>
    <%= form.label :phone do %>
      <%= Spree.t(:phone) %><% if address.require_phone? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.phone_field :phone, class: "form-control #{'required' if address.require_phone?}" , pattern:"[0-9]{7,9}", title: "Ingrese datos validos"  %>
  </p> 

  <% if Spree::Config[:alternative_shipping_phone] %>
    <p class="form-group" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %>
      <%= form.phone_field :alternative_phone, class: 'form-control' , pattern:"[0-9]{7,9}", title: "Ingrese datos validos" %>
    </p>   <% end %>
</div>

app/views/spree/info/contacto.html.erb
<header class="major">
					<h2><b>Contactanos:</b></h2>
					<hr/>
					<p><b>Mail:</b> las3B@gmail.com </p>
					<p><b>Celular:</b> +56975151413</p>
					<p><b>Telefono fijo:</b> 02-27768630</p>
					<p><b>Nombre admnistrador:</b> Victor Gomez</p>
					<div class="6u">
						
							<p><b>Redes sociales:</b><a href="https://www.facebook.com/example"> Facebook</a></p>
							
						</div>
					<hr/>


					
</header>

app/views/spree/info/quienes.html.erb
<h3><b>Tienda Las 3B</b></h3>

<hr/> 

<p>Tienda 3B comienza sus inicios alrededor del año 2014 y consiste, somo un grupo de profesionales capacitados, tenemos una gran experiencia en todo lo que es venta de producto siempre entregando el mejor servicio posible para que nuestros clientes tengan la mejor experiencia de compra.</p>

<hr/>
<br>
<h3><b>¿Cual es la mision de la empresa?</b></h3>

<p>Entregar un servicio de buena calidad, con altos estándares de calidad lo cual le dé al cliente una satisfacción plena a la hora de preferir nuestros servicios.</p>

<hr/>


<h3><b>¿Cual es el objetivo de la empresa?</b></h3>

<p>Ser una de las mejores empresas en su rubro y entregar un servicio diferente a las demás compañías, con una optimización de los procesos .</p>




<hr/>
<header class="major">
<br>
				<h3><b>¿Porqué confiar en nosotros?</b></h3>
					
				</header>
				
				<div class="container">
					
					<div class="row">
						<div class="4u">
<br>
								
								<h4><b>Confiabilidad</b></h4>
								<p>Para nosotros, los clientes son los mas importante, por lo cual nos esmeramos en cumplir con las exigencias de cada uno.</p>
							
						</div>



						<br>
						<div class="4u">
							
								
								<h4><b>Servicio</b></h4>
								<p>Tenemos a lo mejores profesionales en el area, lo cual nos permite entregar un servicio con los mas altos estandares de calidad.</p>
							
						</div>


						<br>
						<div class="4u">
							
								
								<h4><b>Tecnologia De Punta</b></h4>
								<p>Contamos con tecnologia de ultima generacion, para cumplir con todos los requerimientos de nuestros clientes. </p>
							
						</div>

						<br>
						<br>
					</div>
				</div>
			</section>
					

app/views/spree/shared/_link_to_account.html.erb
<% if spree_current_user %>
  <li id="my-account">
  	<a href="/account">Mi Cuenta</a>
  </li>
  <li id="logout">
  	<a href="/logout">Cerrar Sesion</a>
  </li>
<% else %>	
  <li id="link-to-login">
  	<a href="/login">Iniciar Sesion</a>
  </li>
<% end %>

app/views/spree/shared/_main_nav_bar.html.erb
<nav class="col-md-12">
  <div id="main-nav-bar" class="navbar">
    <ul class="nav navbar-nav" data-hook>
      <li id="home-link" data-hook><%= link_to Spree.t(:home), spree.root_path %></li>
      <li id="home-link" data-hook><%= link_to "Quienes Somos", quienes_path %></li>
      <li id="home-link" data-hook><%= link_to "Contacto", contacto_path %></li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right" data-hook>
      <li id="link-to-cart" data-hook>
        <noscript>
          <%= link_to Spree.t(:cart), '/cart' %>
        </noscript>
        &nbsp;
      </li>
      <script>Spree.fetch_cart()</script>
    </ul>
  </div>
</nav>